In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(29)

In [2]:
# Exercises
# 1. How likely is it that you roll doubles when rolling two dice?

# 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 
# What is the probability of getting more than 3 heads?

# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards 
# I drive past both have data science students on them?

# 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending
# machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy
# some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

# 5. Compare Heights

### Men have an average height of 178 cm and standard deviation of 8cm.
### Women have a mean of 170, sd = 6cm.
### Since you have means and standard deviations, you can use np.random.normal to generate observations.
### If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?
### When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the
# installation fails. What are the odds that after having 50 students download anaconda, no one has an installation 
# issue? 100 students?

# 6. What is the probability that we observe an installation issue within the first 150 students that download 
# anaconda?

### How likely is it that 450 students all download anaconda without an issue?

# 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you 
# haven't seen a food truck there in 3 days. How unlikely is this?

### How likely is it that a food truck will show up sometime this week?

# 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 
# 40?

In [3]:
# set number of trials and events per trial

nrows = 100_000 # number of trials
ncols = 2       # number of random events in each trial

In [4]:
# generate an array of randomly generated numbers from 1-6 equal to the number of rows times the number of columns
# to generate all of the values for the study
np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols)

array([6, 4, 5, ..., 5, 6, 5])

In [5]:
# add .reshape to reshape the array by the number of rows and number of columns to create trial groups
rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols)
rolls

array([[2, 6],
       [6, 1],
       [5, 2],
       ...,
       [2, 5],
       [4, 6],
       [3, 2]])

In [6]:
# convert to data frame
df = pd.DataFrame(rolls)
df.head()

0  1
0  2  6
1  6  1
2  5  2
3  5  2
4  6  1

In [7]:
# add .apply create an array that checks weather each row contains matching numbers
df.apply(lambda row: row[0] == row[1], axis=1)

0        False
1        False
2        False
3        False
4        False
         ...  
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 100000, dtype: bool

In [8]:
# add .mean to get the mean of that array to get the odds of rolling doubles on two six sided dice
df.apply(lambda row: row.values[0] == row.values[1], axis=1).mean()

0.16819

In [9]:
# All together
nrows = 100_000 # set nrows to number of simulations
ncols = 2       # set ncolumns to number of dice rolled in each simulation

# create an array of values that represent rollong a six sided dice
# reshape the array into trial groups of 2
rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols) 

# convert the array to a dataframe
df = pd.DataFrame(rolls)

# create an array that returns true if the numbers in each row are equal
# then take the mean of that array to find the total odds of rolling doubles
odds_of_doubles = df.apply(lambda row: row.values[0] == row.values[1], axis=1).mean()
round(odds_of_doubles*100)

17

In [10]:
#2
nrows = 100_000 # set rows to number of simulations
ncols = 8       # set columns to number of random events in each simulation

# create an array of True/False values that represent coin flips True = Heads
# reshape the array into trial groups of 8
rolls = np.random.choice([True, False], nrows * ncols).reshape(nrows, ncols)

# create a dataframe from the array
df = pd.DataFrame(rolls)
df.head()

0      1      2      3      4      5      6      7
0  False  False   True   True   True   True  False   True
1  False  False   True  False   True   True   True   True
2   True   True  False  False   True  False  False  False
3  False  False   True  False   True  False   True   True
4   True   True  False   True  False   True  False   True

In [11]:
# create an array that checks weather the sum of each row contains the desiered number of heads
# then take the mean of that array to find the total odds of flipping the desiered number of heads
three_heads = df.apply(lambda row: row.values.sum() == 3, axis=1).mean()
more_than_three_heads = df.apply(lambda row: row.values.sum() >= 3, axis=1).mean()

round(three_heads*100)


22

In [12]:
round(more_than_three_heads*100)

86

In [13]:
#3
nrows = 100_000 # set rows to number of simulations
ncols = 2       # set columns to number of bilboards in each simulation

# create an array of of values using random choice to repesent weather a given billboard is data science or web dev
# reshape that array into trial groups of 2
rolls = np.random.choice(["DS","WEB","WEB","WEB"], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(rolls)
df.head()

0    1
0  WEB  WEB
1  WEB  WEB
2  WEB  WEB
3  WEB  WEB
4   DS  WEB

In [14]:
# create an array of True/False values that check if both values in each row are data science
# then take the mean of that array to get the probability of driving past two data science signs
both_ds = df.apply(lambda row: (row.values[0] == "DS") and (row.values[1] == "DS"), axis=1).mean()

round(both_ds*100)

6

In [15]:
#4
nrows = 100_000 # set rows to number of simulations
ncols = 5       # set columns to number of days in each simulation

# create an array of values using random.normal to repesent the number of PopTarts bought in a day
# reshabe that array into trial groups of 5 to represent five days or PopTart buying
rolls = np.random.normal(3, 1.5, nrows * ncols).astype(int).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(rolls)
df.head()

0  1  2  3  4
0  2  4  5  2  2
1  2  0  3  5  2
2  1  7  2  2  2
3  0  4  2  3  2
4  3  5  2  1  4

In [16]:
# count the number of bought PopTarts in each row and create a boolean array showing weather the total number of bought PopTarts equals or exceeds 17
# take the mean of the array to get the probability of having poptarts available to by on friday afternoon
odds_of_tarts = df.apply(lambda row: row.values.sum() < 17, axis=1).mean()

round(odds_of_tarts*100)

88

In [17]:
#5 
# use random.normal to create arrays representing male and female hights chosen at random
male_hights = np.random.normal(178, 8, 100_000)
female_hights = np.random.normal(170, 6, 100_000)

# convert the arrays to a to single dataframe where each row reprsents a female and male hight chosen at random
df = pd.DataFrame({"male_hights" : male_hights,
                   "female_hights" : female_hights})

# add boolean column showing true if the female hight is greater in each row (trial)
df['female_is_taller'] = df.female_hights > df.male_hights
df

male_hights  female_hights  female_is_taller
0       178.247404     176.999944             False
1       180.071156     159.447463             False
2       181.345014     171.484457             False
3       184.523630     178.720354             False
4       179.739620     172.680663             False
...            ...            ...               ...
99995   184.364658     165.909327             False
99996   183.069508     173.776766             False
99997   185.426688     167.555213             False
99998   170.271901     171.028522              True
99999   170.787338     164.937110             False

[100000 rows x 3 columns]

In [18]:
# get mean of that column
taller_female = df['female_is_taller'].mean()
round(taller_female*100)

21

In [19]:
#6
nrows = 100_000 # set rows to number of simulations
ncols = 50      # set columns to number of days in each simulation

In [20]:
# create array with each row representing a simulation and each column representing a student in the simulation

# list with 249 falses and one true
issue_range = [False for r in range(1,250)]
issue_range.append(True)

# create array
installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)
installs

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [21]:
# convert to data frame
df = pd.DataFrame(installs)
df.head()

0      1      2      3      4      5      6      7      8      9   ...  \
0  False  False  False  False  False  False  False  False  False  False  ...   
1  False  False  False  False  False  False  False  False  False  False  ...   
2  False  False  False  False  False  False  False  False  False  False  ...   
3  False  False  False  False  False  False  False  False  False  False  ...   
4  False  False  False  False  False  False  False  False  False  False  ...   

      40     41     42     43     44     45     46     47     48     49  
0  False  False  False  False  False  False  False  False  False  False  
1  False  False  False  False  False  False  False  False  False  False  
2  False  False  False  False  False  False  False  False  False  False  
3  False  False  False  False  False  False  False  False  False  False  
4  False  False  False  False  False  False  False  False  False  False  

[5 rows x 50 columns]

In [22]:
# add calculation columnns
df['has_no_problem'] = df.sum(axis=1) == 0
df.head()

0      1      2      3      4      5      6      7      8      9  ...  \
0  False  False  False  False  False  False  False  False  False  False  ...   
1  False  False  False  False  False  False  False  False  False  False  ...   
2  False  False  False  False  False  False  False  False  False  False  ...   
3  False  False  False  False  False  False  False  False  False  False  ...   
4  False  False  False  False  False  False  False  False  False  False  ...   

      41     42     43     44     45     46     47     48     49  \
0  False  False  False  False  False  False  False  False  False   
1  False  False  False  False  False  False  False  False  False   
2  False  False  False  False  False  False  False  False  False   
3  False  False  False  False  False  False  False  False  False   
4  False  False  False  False  False  False  False  False  False   

   has_no_problem  
0            True  
1            True  
2            True  
3            True  
4            True  

[5 rows x 51 columns]

In [23]:
df['has_no_problem'].mean()

0.81823

In [24]:
# All together
nrows = 100_000 # set rows to number of simulations
ncols = 100      # set columns to number of students in each simulation

# list with 249 falses and one true
issue_range = [False for r in range(1,250)]
issue_range.append(True)

# create array with each row representing a simulation and each column representing a student in the simulation
installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(installs)

# add calculation columnns
df['has_no_problem'] = df.sum(axis=1) == 0

# get mean of calculation True/False columns
# format and print results
problems = int(round(df['has_no_problem'].mean(),2) * 100)

problems

67

In [25]:
# All together
nrows = 100_000 # set rows to number of simulations
ncols = 150      # set columns to number of students in each simulation

# list with 249 falses and one true
issue_range = [False for r in range(1,250)]
issue_range.append(True)

# create array with each row representing a simulation and each column representing a student in the simulation
installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(installs)

# add calculation columnns
df['has_a_problem'] = df.sum(axis=1) > 0

# get mean of calculation True/False columns
# format and print results
problems = int(round(df['has_a_problem'].mean(),2) * 100)

problems

45

In [26]:
# All together
nrows = 100_000 # set rows to number of simulations
ncols = 450      # set columns to number of students in each simulation

# list with 249 falses and one true
issue_range = [False for r in range(1,250)]
issue_range.append(True)

# create array with each row representing a simulation and each column representing a student in the simulation
installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(installs)

# add calculation columnns
df['has_no_problem'] = df.sum(axis=1) == 0

# get mean of calculation True/False columns
# format and print results
problems = int(round(df['has_no_problem'].mean(),2) * 100)

problems

16

In [27]:
#7
nrows = 100_000 # set rows to number of simulations
ncols = 3      # set columns to number of days in each simulation

In [28]:
# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([True, False], nrows * ncols, p=[.7,.3]).reshape(nrows, ncols)
sightings

array([[ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True],
       ...,
       [ True,  True,  True],
       [ True,  True, False],
       [False,  True,  True]])

In [29]:
# convert to data frame
df = pd.DataFrame(sightings)
df.head()

0      1      2
0  True   True   True
1  True   True  False
2  True   True   True
3  True  False   True
4  True   True   True

In [30]:
# add calculation columnns
df['times_sighted'] = df.sum(axis=1)
df['not_sighted_three_days'] = df.times_sighted == 0
df.head()

0      1      2  times_sighted  not_sighted_three_days
0  True   True   True              3                   False
1  True   True  False              2                   False
2  True   True   True              3                   False
3  True  False   True              2                   False
4  True   True   True              3                   False

In [31]:
df['not_sighted_three_days'].mean()

0.02736

In [32]:
# get mean of calculation True/False columns
# format and print results
trucks = int(round(df['not_sighted_three_days'].mean(),2) * 100)

trucks

3

In [33]:
# Remaining week days
nrows = 100_000 # set rows to number of simulations
ncols = 2      # set columns to number of students in each simulation

# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([True, False], nrows * ncols, p=[.7,.3]).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(sightings)

# add calculation columnns
df['not_sighted_two_days'] = df.sum(axis=1) == 0

# get mean of calculation True/False columns
# format and print results
trucks = int(round(df['not_sighted_two_days'].mean(),4) * 100)

print(f'The odds of not seeing a food truck in Travis Park for {ncols} days is {trucks}%')

The odds of not seeing a food truck in Travis Park for 2 days is 8%


In [34]:
def food_truck(days):
    
    # Remaining week days
    nrows = 100_000 # set rows to number of simulations
    ncols = days      # set columns to number of days in each simulation

    # create array with each value representing if a food truck has been spotted that day
    # reshape the array into trial groups of the desiered number of days
    sightings = np.random.choice([True, False], nrows * ncols, p=[.7,.3]).reshape(nrows, ncols)

    # convert to data frame
    df = pd.DataFrame(sightings)

    # Sum the number of True values in each row (trial) 
    # create a boolian array that shows true for each row (trial) that had no Trues
    # Take the mean of that array to get the odds of not encountering any trucks in the specified number of days
    no_truck = df.apply(lambda row: row.values.sum() == 0, axis=1).mean()
    
    # Sum the number of True values in each row (trial) 
    # create a boolian array that shows true for each row (trial) that had no Trues
    # Take the mean of that array to get the odds spotting at least one tuck in the desiered number of days
    truck = df.apply(lambda row: row.values.sum() > 0, axis=1).mean()

    print(f'The odds of not seeing a food truck in Travis Park for {days} days is {round(no_truck*100)}%')
  

In [36]:
for r in range(1,8):
    food_truck(r)
    print()

The odds of not seeing a food truck in Travis Park for 1 days is 30%

The odds of not seeing a food truck in Travis Park for 2 days is 9%

The odds of not seeing a food truck in Travis Park for 3 days is 3%

The odds of not seeing a food truck in Travis Park for 4 days is 1%

The odds of not seeing a food truck in Travis Park for 5 days is 0%

The odds of not seeing a food truck in Travis Park for 6 days is 0%

The odds of not seeing a food truck in Travis Park for 7 days is 0%



In [39]:
#8
def shared_birthday(people):

    nrows = 100_000 # set rows to number of simulations
    ncols = people  # set columns to number of people in each simulation

    # create array with each value representing the numbered day of the year that person was born on. (This ignores leap years)
    # reshape the aray into trial groups
    sightings = np.random.choice([r for r in range(366)], nrows * ncols).reshape(nrows, ncols)

    # convert to data frame
    df = pd.DataFrame(sightings)

    # Add boolian column to df showing weather there are less unique numbers in each row (trial) than there are total columns
    df['matching_birthdays'] = df.nunique(axis=1) < ncols

    # get mean of calculation True/False columns
    # format and print results
    matching_birthdays = df['matching_birthdays'].mean()

    # print result
    print(f'The odds of a room of {ncols} people having at least two people that share a birthday are {round(matching_birthdays*100)}%')

In [40]:
num_list = [23, 20, 40]

for num in num_list:
    shared_birthday(num)

The odds of a room of 23 people having at least two people that share a birthday are 51%
The odds of a room of 20 people having at least two people that share a birthday are 41%
The odds of a room of 40 people having at least two people that share a birthday are 89%


In [42]:
x = range(1, 100)

N = [n * (n-1) / 2 for n in x]

y = [1 - (364/365)**n for n in N]